sudo: false

language: python

python:
  - 3.6.4

install:
  - pip3 install -r requirements.txt
  - pip3 install coveralls

script:
  - pytest
  - pylint --disable=cyclic-import ./appserver
  - py.test --cov appserver/

after_success:
  - coveralls
