sudo: false

language: python

python:
  - 3.6.4

install:
  - pip3 install -r requirements.txt
  - pip3 install codecov

script:
  - pytest
  - pylint --disable=invalid-name,too-few-public-methods,import-error
  - coverage erase
  - coverage run ./tests/test_hello_world.py && coverage html

after_success:
  - codecov


