sudo: false

language: python

python:
  - 3.6.4

install:
  - pip3 install -r requirements.txt
  - pip3 install coveralls

script:
  - pytest
  - pylint --disable=invalid-name,too-few-public-methods,import-error,no-self-use *.py ./tests ./api
  - py.test --cov api/

after_success:
  - coveralls


