sudo: false

language: python

python:
  - 3.6.4

install:
  - pip3 install -r requirements.txt
  - pip3 install coveralls

script:
  - pytest
  - pylint --disable=invalid-name,too-few-public-methods,import-error,no-self-use,unused-argument,cyclic-import,wrong-import-position,ungrouped-imports,method-hidden ./appserver
  - py.test --cov appserver/

after_success:
  - coveralls
